### ISSUE TITLE
4.1 RC documentation

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s-enduser#188]
[Copy of the RC changelist](https://github.com/omeka/omeka-s/releases/tag/v4.1.0-rc) as a task list for docs purposes:

## System Requirements

- [x] - Minimum required database versions increased to MySQL 5.7.9 and MariaDB 10.2.6

## Features

- [x] - **Page authoring improvements**
- [x] 	- Grid layout
- [x] 		- Omeka S 4.1.0 adds a new selection when authoring site pages, between the original, older page layout ("Normal flow") and the new Grid layout. Grid uses the native CSS grid feature to provide users with more tools for positioning their content the way they want without needing custom theming or CSS skills.
- [x] 	- Shared block layout settings
- [x] 		- This version also adds a new page editing concept of configuration options that are common to all blocks. Things like alignment and choosing a `class` attribute that were previously implemented piecemeal are avaiable for all blocks, including any added by modules, and modules can also now more easily add their own additionall settings to all blocks
- [x] 		- Among these shared settings is a new background image feature for using assets as backgrounds for any block
- [x] 	- Block templates
- [x] 		- Using the shared layout setting feature (see above), all blocks now provide an option for the author to select from among different templates specific to that block which are provided by the site's chosen theme. This allows themes to provide complex behaviors, styles and customizations that users can choose from with a simple UI. 
- [x] 	- Page templates
- [x] 		- Similar to block templates, the entire page can have a template selected by the author, with the choices also coming from the current theme. Small differences in overall layout or completely custom pages can be created as page templates and exposed for site authors to use.
- [x] 	- New OEmbed page block
- [x] - Performance improvement for performing many "OR"-joined property/value searches at once
- [x] - Site navigation allows user to configure a custom link to open in a new tab/window
- [x] - New settings for controlling appearance of subnavigation on public site pages
- [x] - New batch edit option for setting resource ownership
- [x] - OEmbed media can now be updated
- [x] - Site setting for pre-expanding value annotations
- [x] - Favicon can be selected from assets both globally and per-site
- [x] - Global setting for disabling `@reverse` reverse property listing in API responses
- [x] - Improved mail sending error reporting
- [ ] - Improvements to linked resource display
- [x] - The "fallback" file renderer now respects the same linking settings as the thumbnail renderer
- [x] - Added WebP to the default allowed types for file and asset uploads
- [ ] - Database settings can now be provided via an environment variable OMEKA_DB_CONNECTION_URL rather than database.ini (#1789, contributed by @raboof)

### Admin UI

- [x] - Media upload inputs on item form now accept multiple files selected at once
- [x] - Media upload inputs on item form now show a preview of selected images if the browser can natively display them
- [x] - New direct link to the current user's settings page in left nav
- [x] - Global settings page now divides into more logical groups
- [x] - List of sites for an item now includes a link to go directly to the item's page in each site
- [x] - Asset upload sidebar now indicates the upload size limit
- [x] - Info on free disk space added to system information (#2001, contributed by @Daniel-KM)

## Bugs Fixed

- [x] - Fulltext searches now allow other sorting despite the default relevance-based sort to be chosen; previously doing a fulltext search would override any other sorting selected
- [x] - Fixed TypeError when loading user batch edit (#2100, contributed by @jajm)
- [x] - Fixed some incorrect ARIA accessibility attributes (#2111)
- [x] - Fixed possible deprecation warning when passing null to API `id` search (#2118, contributed by @Daniel-KM)

## Changes

- [x] - HTML media now include their text content in the fulltext index
- [x] - Sorting options now appear first on advanced search
- [x] - Added database index for `is_public` column for several key tables (#2105, contributed by @Daniel-KM)

### Changes

- [x] - New "fallback setting" service and helpers for looking for same-named options in multiple contexts (global, site, user settings)
- [x] - Element groups feature is now enabled and used on batch edit forms
- [x] - Automated tests now run against PHP 8.3 additionally (#2125, contributed by @Daniel-KM)
- [x] - `aria-label` property now automatically set for translation for Laminas form selects (#2120, contributed by @Daniel-KM)
- [x] - Login will not redirect to dashboard if user does not have permission to view dashboard (#1961, contributed @jajm)

**Comment by sharonmleon** [comment]
@allanaaa I have started a very barebones version of documentation for the page layouts on the grid branch. The operative edits are on Site Pages file.

**Comment by allanaaa** [comment]
- [ ] Media embed / item showcase merge
- [ ] Preview layout on page edit 
- [ ] Background colours on page blocks

and other things from https://github.com/omeka/omeka-s/issues/2148

**Comment by allanaaa** [comment]
- [ ] TOC changes as per https://github.com/omeka/omeka-s/issues/2145
- [ ] Site thumbnail advice
- [ ] Some advice on the oEmbed block - including that sources define their own display sizes and cannot be customized (Vimeo, Youtube, etc. as examples)

**Comment by allanaaa** [comment]
- [ ] "Page subnavigation display" on site settings and how it works with different themes

**Comment by allanaaa** [comment]
I think we'll keep the new Mapping module as a separate docs PR even though I imagine it'll get released pretty quickly after 4.1.

re: https://github.com/omeka-s-modules/Mapping/issues/119

**Comment by allanaaa** [comment]
@katknow Also, or perhaps instead, you can write a new section for the oEmbed page block?

This one is pretty simple to document as far as its settings go, but because there's very little configuration, we need to warn people about how things will display. 

It would be good to have a list of the most popular oEmbed-enabled services. 

Try it with a Flickr link, a Youtube link, Vimeo, maybe one or two others, and document what those services allow you to do - mainly that they send a hardcoded size that users can't really modify unless they stick it in a smaller container. Mention that normal (a float) and grid (any column span they choose) will behave a little differently.  

Also mention that you can't save the page without any URL in the oEmbed block, and you can't rewrite the URL after you put one in.

**Comment by allanaaa** [comment]
The original to-do list is pretty much done - waiting on some changes to ilnked resource display. 

Need to elaborate a bit more on what page templates and block templates do, although there aren't a lot of examples of it in action so far. And need to review the testing issue https://github.com/omeka-s-themes/foundation/issues/63.

This PR is otherwise ready to be read over, @sharonmleon @zerocrates @jimsafley @katknow, with the original RC list in mind and with all the changes made since then (https://forum.omeka.org/t/omeka-s-4-1-release-candidate/20728 and https://github.com/omeka/omeka-s/releases/tag/v4.1.0-rc).
